version: '3.7'
services:
 mysql:
  build: ./mysql/
  cap_add:
      - SYS_NICE
  container_name: Full2020-86287
  restart: always
  environment:
   MYSQL_DATABASE: SFornal
   MYSQL_USER: SFornal
   MYSQL_PASSWORD: SFornal
   MYSQL_ROOT_PASSWORD: SFornal
  ports:
   - 3306:3306
  networks:
   BridgeZadanie1:
      ipv4_address: 10.0.10.3

 java:
  image: simonf1997/docker_java_app
  container_name: AppContainer
  depends_on:
   - mysql
  networks:
   - BridgeZadanie1
  stdin_open: true
  tty: true


volumes:
  db-data:

networks:
 BridgeZadanie1:
  driver: bridge
  ipam:
   config:
    - subnet: 10.0.10.0/24